# Generated by Django 6.0.2 on 2026-03-02 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_address', models.TextField(blank=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=254)),
                ('vendor_phone', models.CharField(blank=True, max_length=50)),
                ('po_number', models.CharField(blank=True, max_length=100, verbose_name='PO Number')),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('subtotal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('ZAR', 'South African Rand')], default='USD', max_length=10)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('archived', 'Archived')], default='uploading', max_length=20)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('ai_flag_message', models.TextField(blank=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('processing_progress', models.IntegerField(default=0)),
                ('processing_current_step', models.IntegerField(default=1)),
                ('processing_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_invoices', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing_started', 'Processing Started'), ('processing_complete', 'Processing Complete'), ('processing_failed', 'Processing Failed'), ('field_viewed', 'Field Viewed'), ('field_corrected', 'Field Corrected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('exported_csv', 'Exported as CSV'), ('exported_json', 'Exported as JSON'), ('sent_to_accounting', 'Sent to Accounting'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=30)),
                ('detail', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoices.invoice')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ai_confidence', models.FloatField(default=1.0)),
                ('sort_order', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoice_line_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=100)),
                ('extracted_value', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('manually_corrected', models.BooleanField(default=False)),
                ('corrected_value', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='invoices.invoice')),
            ],
            options={
                'db_table': 'extracted_fields',
                'unique_together': {('invoice', 'field_name')},
            },
        ),
    ]
