# Generated by Django 6.0.2 on 2026-03-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing_started', 'Processing Started'), ('processing_complete', 'Processing Complete'), ('processing_failed', 'Processing Failed'), ('field_viewed', 'Field Viewed'), ('field_corrected', 'Field Corrected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('exported_csv', 'Exported as CSV'), ('exported_json', 'Exported as JSON'), ('exported_excel', 'Exported as Excel'), ('exported_pdf', 'Exported as PDF'), ('sent_to_accounting', 'Sent to Accounting'), ('archived', 'Archived'), ('deleted', 'Deleted')], max_length=30),
        ),
    ]
