# Generated by Django 6.0.2 on 2026-03-02 17:19

import apps.documents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=apps.documents.models.invoice_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_data_points_found', models.IntegerField(blank=True, null=True)),
                ('ocr_completed_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_provider', models.CharField(blank=True, max_length=50)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoice_documents',
            },
        ),
    ]
